# Generated by Django 4.2.11 on 2024-04-14 04:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0003_remove_produto_preco_produto_codigo_barras_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AtualizacaoEstoque',
        ),
    ]
